# Generated by Django 5.1 on 2024-08-22 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='cid',
            field=models.ForeignKey(db_comment='This column stores the customer id.', default=1, on_delete=django.db.models.deletion.CASCADE, to='core.customer'),
        ),
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.CharField(blank=True, default='', help_text='This is the type of the document.', max_length=254, verbose_name='Document Type'),
        ),
    ]
